### PR TITLE
Added cloud IDs to LinkPropertyLookupTable

### PR DESCRIPTION
**Pull request by amilan17**
AWS:S3, Google:BigQuery and Google:GCS

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@tomkralidis , okay to merge?

**Comment by rsignell-usgs** [comment]
@amilan17 this is minor, but why "AWS", but "Google".   Seems like either "AWS/GCE" or "Google/Amazon" would be more parallel form.

**Comment by amilan17** [comment]
Hi Rich,
Thanks for the suggestion. I think that's a reasonable request. My
colleague suggests using GCP instead of GCE...

"I agree the namespace for Google could be improved/more specific. However,
> it looks like GCP for Google Cloud Platform might be an appropriate
> namespace to use here, because BigQuery, Google Cloud Storage (GCS) and
> Google Compute Engine (GCE) are listed as GCP products
> <https://cloud.google.com/products/>.
> The two protocol names would become,
> GCP:BigQuery
> GCP:GCS"


If this still makes sense, I can change the pull request.


Anna
*~~~~~~Metadata Adds Meaning~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Comment by tomkralidis** [comment]
OK so I misread @rsignell-usgs.  Note there is nothing wrong with using multiple qualifiers, e.g. 

- `Google:GCP:GCS`
- `Google:GCP:BigQuery`
- `Amazon:AWS:S3`

**Comment by dneufeldcu** [comment]
@tomkralidis ok, this is already to go, let's merge!

**Comment by rsignell-usgs** [comment]
@tomkralidis , looks good to me also.

**Comment by amilan17** [comment]
Thank you!

Anna
*~~~~~~Metadata Adds Meaning~~~~~~*
Anna.Milan@noaa.gov, 303-497-5099
NOAA National Centers for Environmental Information
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

**Pull request merged**
